version: "3.8"

services:
    user_db:
        build: ./src/user/db
        container_name: user_db
        restart: unless-stopped
        ports:
            - "5432:5432"
        env_file:
            - ../../.env
        volumes:
            - user_db-data:/var/lib/postgresql/data
        networks:
            - nginx_network

volumes:
    user_db-data:

networks:
    nginx_network:
        external: true