services:  
  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - ./sources/frontend/html:/usr/share/nginx/html
    ports:
      - "443:443"
    networks:
      - app_network
    
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app_network
  
  pg-admin:
    image: elestio/pgadmin:latest
    container_name: pg-admin
    environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - app_network
  
networks:
  app_network:
    name: app_network
    driver: bridge

volumes:
  db-postgres: