services:  
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/var/www/html
    ports:
      - "443:443"
    depends_on:
      - backend
      - postgres
    networks:
      - app_network
    
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-postgres:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build:
      context: ./sources
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - UID=${UID}
      - SECRET=${SECRET}
      - URI=${URI}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - DEFAULT_EMAIL_SENDER=${DEFAULT_EMAIL_SENDER}
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - app_network
      
networks:
  app_network:
    name: app_network
    driver: bridge

volumes:
  db-postgres:
