services:  
  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - ./sources/frontend/static/html:/usr/share/nginx/html
    ports:
      - "443:443"
    networks:
      - app_network
    
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app_network

networks:
  app_network:
    name: app_network
    driver: bridge

volumes:
  db-postgres: