# Generated by Django 5.1.5 on 2025-01-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_user_nickname_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_logged_in",
            field=models.BooleanField(default=True),
        ),
    ]
