<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-01-21 14:15
=======
# Generated by Django 5.1.5 on 2025-01-22 00:57
>>>>>>> bf524791c09d3489bbdae5acce8e37da1fc369f5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("app", "0002_user_groups_user_is_active_user_is_staff_and_more"),
=======
        ('app', '0002_user_groups_user_is_active_user_is_staff_and_more'),
>>>>>>> bf524791c09d3489bbdae5acce8e37da1fc369f5
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name="user",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="./photos/"),
=======
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
>>>>>>> bf524791c09d3489bbdae5acce8e37da1fc369f5
        ),
    ]
