# Generated by Django 5.1.5 on 2025-01-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_user_is_logged_in"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_logged_in",
            field=models.BooleanField(default=False),
        ),
    ]
