# Generated by Django 5.1.5 on 2025-01-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_user_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="photo",
        ),
    ]
