# Generated by Django 5.1.5 on 2025-01-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_user_is_logged_in"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_logged_in",
        ),
    ]
