# Generated by Django 5.1.5 on 2025-01-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_user_is_logged_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="online",
            field=models.BooleanField(default=True),
        ),
    ]
