# Generated by Django 5.1.5 on 2025-01-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_twofactorauth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='two_fa_enable',
        ),
        migrations.DeleteModel(
            name='TwoFactorAuth',
        ),
    ]
