# Generated by Django 5.1.5 on 2025-01-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_rename_created_at_user_created_remove_user_groups_and_more"),
        ("app", "0008_alter_user_photo"),
    ]

    operations = []
