# Generated by Django 5.1.5 on 2025-01-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_user_two_fa_enable_delete_twofactorauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_fa_enable',
            field=models.BooleanField(default=False),
        ),
    ]
