# Generated by Django 5.1.5 on 2025-01-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_user_two_fa_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_fa_enable',
            field=models.BooleanField(default=False),
        ),
    ]
