# Generated by Django 5.1.5 on 2025-01-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_user_two_fa_enable_twofactorauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='two_fa_enable',
            field=models.BooleanField(default=True),
        ),
    ]
