version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./sources/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./sources/backend:/app
    env_file:
      - .env
    networks:
      - app_network
  
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - app_network

  nginx:
    container_name: nginx
    build:
      context: ./sources/nginx
      dockerfile: Dockerfile
    volumes:
      - ./sources/frontend:/usr/share/nginx/html
    ports:
      - "443:443"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  db-postgres:

networks:
  app_network:
    name: app_network
    driver: bridge