# Generated by Django 5.1.4 on 2024-12-21 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_games_gametype_match_matchparticipant_tournament_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="gameID",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="myapp.games"
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="gameTypeID",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.gametype",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="tournamentID",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.tournament",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="userID",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
            ),
        ),
        migrations.AddField(
            model_name="matchparticipant",
            name="matchID",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="myapp.match"
            ),
        ),
        migrations.AddField(
            model_name="matchparticipant",
            name="userID",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="myapp.user"
            ),
        ),
    ]
